### ISSUE TITLE
rhel sysvinit :disable action mis-checks status every chef-client run

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/mysql#274]
Stock status function probably doing something stupid. Needs replacing.

**Comment by kamaradclimber** [comment]
any progress on that ticket?

**Comment by someara** [comment]
None yet... been swamped with other things.
The fix for this would involve rewriting / patching the stock sysvinit scripts on EL5, EL6, and Amazon.

-s

**Comment by someara** [comment]
Come to think about it, I bet we can just use the one in templates/default/sysvinit/mysqld.erb

**Comment by kamaradclimber** [comment]
Don't you already do that ?
(https://github.com/chef-cookbooks/mysql/blob/master/libraries/provider_mysql_service_sysvinit.rb#L8)

**Comment by jblaine** [comment]
FWIW, I cannot reproduce this on RHEL 6.6 using version 6.0.10 of this cookbook and Chef 11.18.0.

I had some trouble until I used the following per the README example:

    mysql_service "default" do
      action [:create, :start]
    end

And not just:

    mysql_service "default"

**Comment by someara** [comment]
reworded this to: rhel sysvinit :disable action mis-checks status every chef-client run

**Comment by someara** [comment]
This should be fixed up here
https://github.com/chef-cookbooks/mysql/commit/d41dd64de8e6f091cab8e1937d87c3a17f313b0c#diff-949207b026550f56dedf4decaf6450d7R116
