### ISSUE TITLE
@config params not found

### ISSUE THREAD

**Issue by malnick** [chef-cookbooks/mysql#277]
Hi there, I can't tell if this is an issue with the mysql cookbook or my architecture. I'm deploying a mysql instance with [this](https://github.com/malnick/homework/blob/master/chef/cookbooks/digitalocean/recipes/default.rb#L16). 

I followed the basic example you guys have in the readme, with one small modification since it couldn't find the my.cnf.erb in the mysql cookbook, I placed it in my digitalocean cookbook templates folder. 

Then when I ran it, I got [this](https://gist.github.com/malnick/fbead59af691e4f5fc4b) output. It can't find the @config.anything. At first, it was @config.name, which should default to the resource name 'default'. I tried using the config_name to force it and it still failed. Then I removed any reference to @config.name and it just went to the next @config parm in the template @config.charset, also not found. 

I assumed that this meant it could not find anything in the @config instance. 

Any help to get me going on this would be great.

Thanks.

**Comment by someara** [comment]
Hi. 

The mysql_config resource is just a wrapper around the template resource that calculates the path of the conf.d directory so you don't have to.

You need to bring your own config.

Look in the test fixtures for examples.
https://github.com/opscode-cookbooks/mysql/tree/master/test/fixtures/cookbooks

Is there a way I could reword the README so that this is more clear?

-s

**Comment by ernie58** [comment]
I'm having the same issues.
When I leave out the mysql_config part, the recipe works, but I can't get my mysql-server running, because there's is no my.cnf file.

When i leave it in, i get the same config-variable errors:

this is my config:

mysql_service 'default' do
  port '3306'
  version '5.5'
  initial_root_password 'ch4ng3m3'
  action [:create, :start]
end

mysql_config 'default' do
  source 'my.cnf.erb'
  instance 'localhost'
  notifies :restart, 'mysql_service[default]'
  action :create
end

**Comment by someara** [comment]
You're supposed to bring your own template source for the mysql_config
resource... the my.cnf.erb in the mysql cookbook is for internal use by the
mysql_service resource.

please see test/fixtures/cookbooks for examples.

**Comment by ernie58** [comment]
Thx for the help. I've looked into the fixtures and updated my recipes, their identical to the fixtures now. Everything installs fine, but I still have one problem. When I ssh into my node I can't start the mysql server. 

vagrant@packer-virtualbox-iso:~$ sudo /etc/init.d/mysql start
[warn] /etc/init.d/mysql: WARNING: /etc/mysql/my.cnf cannot be read. See README.Debian.gz ... (warning).
[FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . failed!

Apparently there is no my.cnf, so I'm guessing I'm still doing something wrong in my recipe?

**Comment by someara** [comment]
You need /etc/mysql-<instance_name>/mysql start

From your recipe...  /etc/mysql-default/mysql start

-s

**Comment by casertap** [comment]
Hi, I am in the same situation now.
When I try to connect to mysql
```
$ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

$ sudo service mysql-default status
mysql-default is running

$ sudo su
$ cat /etc/mysql-default/my.cnf

# Chef generated my.cnf for instance mysql-default

[client]
default-character-set          = utf8
port                           = 3306
socket                         = /run/mysql-default/mysqld.sock

[mysql]
default-character-set          = utf8

[mysqld]
user                           = mysql
pid-file                       = /run/mysql-default/mysqld.pid
socket                         = /run/mysql-default/mysqld.sock
bind-address                   = 0.0.0.0
port                           = 3306
datadir                        = /var/lib/mysql-default
tmpdir                         = /tmp
log-error                      = /var/log/mysql-default/error.log
!includedir /etc/mysql-default/conf.d

[mysqld_safe]
socket                         = /run/mysql-default/mysqld.sock

$ cd  /run/mysql-default/
$ ls
mysqld.pid  mysqld.sock
````

How can I connect to the mysql console?
The mysql command is trying to check at this path '/var/run/mysqld/mysqld.sock' but it is a mysql-default instance that is started with a sock file at '/run/mysql-default/mysqld.sock'

**Comment by ernie58** [comment]
This works for me:
mysql -h 127.0.0.1 -u root -p******* -P3306

**Comment by casertap** [comment]
thanks it worked.
this worked too: 
```
mysql --socket=/run/mysql-default/mysqld.sock -u root -p
````
