### ISSUE TITLE
Still not fixed: undefined method `parsed_data_dir' for Chef::Resource::MysqlService

### ISSUE THREAD

**Issue by Umofomia** [chef-cookbooks/mysql#284]
It looks like there's still a problem with fix #283 by @arosenhagen that attempted to fix #282. The template attempts to retrieve `parsed_data_dir` from `@config`, but the fix passes it in to the template directly as `@parsed_data_dir`.

Either the template needs to be changed to use `@parsed_data_dir`, or `parsed_data_dir` needs to be added to `@config`. I'm not yet too familiar with the conventions in this cookbook to know which is the better fix, but would be happy to contribute a pull request if advised.

**Comment by someara** [comment]
.... and this is why I need to start rendering the templates in ChefSpec.
On it...

**Comment by Umofomia** [comment]
Following the example already set by https://github.com/chef-cookbooks/mysql/blob/8a3f48c447d9800e45b537f59dca9cfe07477bb2/libraries/provider_mysql_service.rb#L231, it appears the right fix might be to pass the variable into the template as `data_dir` and have the template use `@data_dir`.

**Comment by someara** [comment]
Fixed in master here

https://github.com/chef-cookbooks/mysql/commit/b2c35b3e6d2c6abced6a040dac664b6c567f6f1e

Running full integration test suite before releasing

-s

**Comment by arosenhagen** [comment]
sry...was a bit too fast on it :-/

**Comment by Umofomia** [comment]
Thanks @someara! I really appreciate it.

@arosenhagen No problem, it happens to all of us. :smile:

**Comment by someara** [comment]
Released as 6.0.10
