### ISSUE TITLE
Typo/Error in sysvinit startup script

### ISSUE THREAD

**Issue by joerg** [chef-cookbooks/mysql#290]
There is a simple type in the sysvinit startup script. The start_failure does action true while of course it should do false. This way on a failure it prints [OK] and returns 1 while it should print [FAILURE]. Since this is so minor I will not send a pull request. ;)
```ruby
print_start_failure() {
<% if node['platform_family'] == 'rhel' %>
- action $"Starting <%= @mysql_name %>: " /bin/true
+ action $"Starting <%= @mysql_name %>: " /bin/false
<% else %>
```

**Comment by someara** [comment]
Fixed in master. Thanks!

PS: in the future, this kind of thing falls under the "obvious fix policy", and doesn't need a CLA check =)
