### ISSUE TITLE
CentOS Support?

### ISSUE THREAD

**Issue by tomflanagan** [chef-cookbooks/mysql#300]
Does this work for CentOS? I can't seem to figure this out. I want to make sure there isn't a bug.

**Comment by someara** [comment]
Yes. Please refer to the testing matrix in README.md

**Comment by tomflanagan** [comment]
Ok Using the examples in the README.md to create a recipe hasn't worked for me. I'm new to chef, is there an example most cookbooks I have used had recipes included with them.

**Comment by someara** [comment]
Hi.

This cookbook ships resource types to use in recipes, but no actual recipes.
You can use the cookbooks in the test fixtures.. check out:

https://github.com/chef-cookbooks/mysql/tree/master/test/fixtures/cookbooks/mysql_service_test

-s

**Comment by tomflanagan** [comment]
Although it provisions and mysql installs, I can't seem to start it. I get Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2). A CentOS issue maybe?

**Comment by someara** [comment]
The mysql_service resource uses "non-standard" paths for things like
sockets, so it can support multiple instances on a single machine.

Go looking in /var/lib/mysql*
The path depends on what you named the instance.

The easiest thing to do is to connect over a tcp socket via 127.0.0.1

-s

**Comment by tomflanagan** [comment]
var/lib/mysql does not have mysql.sock however I see something at /var/run/mysql-default/mysqld.sock. I really not sure what is going on here. /etc/mysql-default/my.cnf has the socket = /var/run/mysql-default/mysqld.sock. Yet it is still trying to run on /var/lib/mysql/mysql.sock. It seems to be ignoring my.cnf.

**Comment by someara** [comment]
If you named your mysql_service "default", then the service's config is at
/etc/mysql-default/my.cnf.

This will contain the bare minimum configuration to get the service running
(including the socket, pointing to  /var/run/mysql-default/mysqld.sock),
and loading extra configuration out of  /etc/mysql-default/conf.d.

A mysql_config named "default" will render your source template into
/etc/mysql-default/conf.d/default.cnf.

A mysql_config named "foo" will render your source template into
/etc/mysql-default/conf.d/foo.cnf.

You should put all *further* configurations into the conf.d directory.

I'd love to clarify how this works in the README, but I'm not sure how to
word it any more simply.

Suggestions welcome.

-s

**Comment by tomflanagan** [comment]
I solved the problem by explicitly defining the location of mysql.sock. So I did this :
mysql_service 'default' do
  version node['mysql']['version']
  socket '/var/lib/mysql/mysql.sock'
  initial_root_password 'Ch4ng3me'
  action [:create, :start]
end

**Comment by idanappxoee** [comment]
@tomflanagan 

Note that this might not work on all Linux variants. For example, Ubuntu clears /var/run on each restart, and creates them based on the service name.

**Comment by francis2211** [comment]
I am still getting the error
    Unknown MySQL server host '/var/run/mysql-default/mysqld.sock' (1)
and the mysqld.sock is on that directory.
