### ISSUE TITLE
selinux support

### ISSUE THREAD

**Issue by joerg** [chef-cookbooks/mysql#305]
For all service providers the creation of init scripts should be in a separate :create action and not in :start. That way it would be possible to execute certain steps before the service actually starts (e.g. selinux).

```ruby
mysql_service instance do
  version node['mysql']['version']
  data_dir instance_data
  initial_root_password root_password
  action :create
end

... some code to set selinux file context

service "mysql-#{instance}" do
  action :start
end
```

Currently this is not possible, because the init script does not exists when just creating the service. Also, when starting the service without setting the selinux file context the service can not start and throws an error.

**Comment by someara** [comment]
I agree that selinux should be handled...  but it should be handled inside the actions.

The `mysql_service` and `mysql_config` resources dynamically calculate disk paths as part of their internal implementation. Forcing the user to manage their own selinux labels (and the OS service state, in your example) from the outside creates a leaky abstraction, where the user needs to actually look at, understand the implementation, and duplicate some internal logic of the providers. 

In some cases, it may not be possible to fix it from the outside at all.
Imagine the case (yet to be implemented):

```
mysql_service 'whatever' do
  port '3308'
  provider Chef::Provider::MysqlService::Container
  action [:create, :start]
```

multiply that times multiple instances on the same machine systemd and things get weird.

What is the best way to set the labels?
 
`semanage fcontext -a -e /etc/mysql /etc/#{mysql_name}` ?

**Comment by joerg** [comment]
I've alredy written a simple fcontext provider for [selinux-policy](https://github.com/BackSlasher/chef-selinuxpolicy/pull/3) but I need to change some minor stuff an finally create a new pull request. The Readme also contains an example on how to use it with mysql.
The Problem I recently stumbled upon is, that selinux expects every folder to be under a certain context. So having the mysql data in /var/app-db is fine, because /var is "opened" by default. Having it in /var/app/db you need to add /var/app _and_ /var/app/db under a certain context. It can not be simply done recusivly, because there could be other data in /var/app and choosing under which file context to put /var/app automatically might be problematic. This is why I think letting the user decide which seliunux contexts to use might be best.
But I have to state that I am not really experienced with selinux, so maybe I am worrying to much...

**Comment by sernapallyanurag** [comment]
============================================================================
====
    Error executing action `start` on resource 'mysql_service[default]'
    ============================================================================
====

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    service[default :start mysql-default] (/var/chef/cache/cookbooks/mysql/libra
ries/provider_mysql_service_sysvinit.rb line 26) had an error: Mixlib::ShellOut:
:ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/service mysql-default start ----
    STDOUT: Starting mysql-default (via systemctl):  [FAILED]
    STDERR: Job for mysql-default.service failed. See 'systemctl status mysql-de
fault.service' and 'journalctl -xn' for details.
    ---- End output of /sbin/service mysql-default start ----
    Ran /sbin/service mysql-default start returned 1

I am using Centos 7.1 in azure and SElinux is disabled still I get this error
