### ISSUE TITLE
feature request: support instance name

### ISSUE THREAD

**Issue by stevenolen** [chef-cookbooks/mysql#307]
Would it be possible to support an `instance` string attribute for the `mysql_service` lwrp like the httpd cookbook supports (where you can name the instance, or leave it out to use the distro's default), so we can implement v6 of this cookbook on existing default installs (and existing installs which used v5 of this cookbook). Thanks for the awesome re-write (and apologies if there's already been an issue for this -- I couldn't find one)! 

https://github.com/chef-cookbooks/httpd#parameters

**Comment by someara** [comment]
Hi Peter. mysql_service and mysql_config already support the instance parameter. Have a look around in test/fixtures/cookbooks for some concrete examples. 




You can point the data_dir at the old 5.x location for an in place upgrade (always test first!)




httpd *used* to try and keep default paths on the 'default' instance, but now works like mysql, so nobody gets hurt during package upgrades. 




I may have forgot to reflect that in the docs... I'm afk at te moment but will check next week. 




In the mean time be aware that PRs on documentation are my favorite kind =)




-s



—

**Comment by someara** [comment]
Er. Steve. Sorry!



—
