### ISSUE TITLE
Make 'default' service and instance backwards compatible with older cookbook versions

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/mysql#312]
Hello! Would there be any interest in a backwards-compatible behavior for this cookbook, where if the instance name is 'default', the older paths and names are used. For example, if the service is named 'default', the init script would be `/etc/init.d/mysqld` instead of `/etc/init.d/mysql-default` on CentOS.

This would provide a layer of backwards compatibility for those trying to upgrade. Just wanted to gauge interest before doing the work. Thanks all!

**Comment by someara** [comment]
Hi Martin!

This is one of those things that needs to be added to the README for
clarification...

The 6.x resources purposefully use non-standard paths.

At first, this was mostly to deal with Debian packaging post scripts, but
it eventually proved useful for dealing with upstream package vendors
changing things as well.

The 6.x mysql_service resources also shut down the system "native" service
when applicable, so 'service mysql' won't conflict with 'service
mysql-default'.

You should be able to do a upgrade by pointing a 6.x mysql_service resource
at the same data_dir as a 5.x mysql_resource. Unfortunately, they will have
different (calculated) default paths.

-s

**Comment by martinb3** [comment]
@someara Thank you for the clarification. It sounds like there were reasons beyond just allowing multiple instances of MySQL on the same host. I'll hold off for now :)
