### ISSUE TITLE
Broken local MySQL  access notes are unclear

### ISSUE THREAD

**Issue by nkadel-skyhook** [chef-cookbooks/mysql#314]
The local MySQL access breaks because the forcible installation of specific instances, rather than touching the default /etc/my.cnf, forces a deletion of /etc/my.cnf to avoid confusion among multiple instances. MySQL is basically hardcoded to read /etc/my.cnf on *all* client and server operations, even if another config file is specified on the command line, so deleting it is understandable.

I've submitted https://github.com/chef-cookbooks/mysql/pull/313 to provide more detail in the README.md.

**Comment by someara** [comment]
Merged. Thanks!
