### ISSUE TITLE
sudo service mysql start not worked

### ISSUE THREAD

**Issue by zanjibar** [chef-cookbooks/mysql#315]
Recently serivce mysql responses are something wrong
mysql status    -> mysql stop/waiting 
mysql start       -> start: Job failed to start
mysql stop       -> stop:Unknow instance:

how could I fix it.

**Comment by someara** [comment]
If you used  mysql_service 'default', the service is named "mysql-default".

**Comment by zanjibar** [comment]
"sudo service mysql-default"
response is
"mysql-default: unrecognized service"

checcking    "sudo service --status-all" 
I found 
 "[ ? ]  mysql"

checking "service apparmor status"
I found mysql !
   "/usr/sbin/mysqld"

about apparmor and mysql relation in detail,where could I find ?

**Comment by zanjibar** [comment]
OS is Ubuntu 14.04.1 LTS

**Comment by fragtom** [comment]
same to me.. my service mysql-spdy doen't upstart right.. in log I could see:

malta1757:# service mysql-spdy start
Mar 21 23:03:09 malta1757 kernel: [93498.159550] init: mysql-spdy main process (1003) terminated with status 1
Mar 21 23:03:09 malta1757 kernel: [93498.159557] init: mysql-spdy main process ended, respawning

**Comment by fragtom** [comment]
have similar problem, could find my prob in log..  /var/log/mysql/error.log...

**Comment by someara** [comment]
can you gist your recipe?

**Comment by fragtom** [comment]
have still several problems with permissions on not-default environment

mysql_service node['spdy_base']['mysql']['name'] do
  action [:create, :start]
  data_dir "/mnt/data/mysql-spdy"
  initial_root_password node['spdy_base']['mysql']['pass']
  run_user node['spdy_base']['mysql']['user']
  run_group node['spdy_base']['group']
  port '3306'
  version '5.6'
end

mysql_config 'spdy' do
  action :create
  instance node['spdy_base']['mysql']['name']
  #notifies :reload, 'mysql_service[spdy]'
  source 'mysql.spdy.cnf.erb'
end

> Am 21.03.2015 um 23:13 schrieb Sean OMeara <notifications@github.com>:
> 
> can you gist your recipe?
> 
>

**Comment by fragtom** [comment]
entry in syslog:

Mar 21 23:18:49 malta1757 kernel: [94438.734739] init: mysql-spdy main process (4918) terminated with status 1
Mar 21 23:18:49 malta1757 kernel: [94438.734747] init: mysql-spdy main process ended, respawning

**Comment by someara** [comment]
Have you created your system users ala
https://github.com/chef-cookbooks/mysql/blob/master/test/fixtures/cookbooks/mysql_service_test/recipes/multi.rb

-s

**Comment by fragtom** [comment]
yes, I’ve created that via user .. 

# # create user
user node['spdy_base']['mysql']['user'] do
  action  :create
  group   node['spdy_base']['group']
  system  true
end


I’ve done reset on my  ubuntu installation and added to cookbook 
mysql_service 'default' do
  action :delete
end

now it works.

**Comment by DrMerlin** [comment]
What mysql* init scripts do you have under /etc/init?

My 'mysql-default' service starts fine, but it's not listed under 'service --status-all'.  Like yours, that just shows a non startable mysql.

**Comment by someara** [comment]
"service" is a wrapper around the sysvinit system.

This cookbook uses the upstart provider on ubuntu-14.

I think you're looking for initctl list | grep mysql

-s

**Comment by fragtom** [comment]
on my system it works under mysql-*myname* ..

```server:~# initctl list | grep mysql
mysql-spdy start/running, process 13768
mysql stop/waiting
```

**Comment by someara** [comment]
This is expected behavior
