### ISSUE TITLE
Need matcher for testing config file contents from mysql_config

### ISSUE THREAD

**Issue by markgloshen** [chef-cookbooks/mysql#322]
The mysql_config LWRP is intended to be used in other cookbooks yet there is no way to use ChefSpec in another cookbook to test the contents of the config file resulting from this.  The reason being that LWRP are not executed by ChefSpec unless they are stepped into and stepping into an LWRP from another cookbook is not allowed.

To allow testing of an LWRP from another cookbook a custom matcher should be provided in the LWRP's cookbook.  There are already custom matchers for create_mysql_config and delete_mysql_config but there are no matchers for testing the resulting template contents.

When adding a matcher for testing it would be nice if it could also test contents of ini sections.  There is a good example of this in this stackforge cookbook:  https://github.com/stackforge/cookbook-openstack-common/blob/master/libraries/matchers.rb

**Comment by tas50** [comment]
Matchers are present in master / the released version of the cookbook
