### ISSUE TITLE
[BUG] Mysql is not running after first provisioning

### ISSUE THREAD

**Issue by ernsto** [chef-cookbooks/mysql#325]
Here is a reference to the original issue: r8/vagrant-lamp#118

**My test environment**
I tested your cookboock in a vagrant ubuntu environment in which i used only the cookbooks mysql, apt and build-essential**

I created a **repo** for you with that you can easily reproduce the bug: https://github.com/ernsto/vagrant-cookbook-mysql-test

Here are some codesnippets of my test vagrant systems: 

**./Berksfile:**
```
source "https://supermarket.getchef.com"
cookbook 'apt', '~> 2.6.1'
cookbook 'mysql', '~> 6.0.20'
```

**./cookbooks/vagrant_main/recipes/default.rb**
```
include_recipe "apt"
include_recipe "build-essential"
# Install Mysql
mysql_service 'default' do
  port '3306'
  version '5.5'
  initial_root_password 'vagrant'
  action [:create, :start]
end
mysql_config 'default' do
  source 'mysite.cnf.erb'
  notifies :restart, 'mysql_service[default]'
  action :create
end
```

**./cookbooks/metadata.rb**
```
depends          "apt"
depends          "build-essential"
depends          "mysql", "~> 6.0"
```

**THE RESULT**
```
`vagrant@vagrant:/vagrant/public/local.dev$ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
vagrant@vagrant:/vagrant/public/local.dev$ sudo service mysql start
start: Job failed to start`
```

**Comment by someara** [comment]
Looks like you're probably overriding the socket config in your mysite.cnf.erb.
Try omitting it and letting the resource handle it

**Comment by someara** [comment]
Also, refer to the example cookbooks in test/fixtures/cookbooks

**Comment by ernsto** [comment]
A mysite.cnf.erb does not exist. As you can see in the directory cookbooks/vagrant_main/templates/default of the repository mentioned above there is no such file. Could this be the reason for the bug?

**Comment by FungaiP** [comment]
I also get the same error. Why can't you guys write a simpler cookbook like everybody else. So frustrating...

**Comment by rw355** [comment]
I also got the same error in a fresh clone and vagrant up.

**Comment by someara** [comment]
You have to bring your own mysite.cnf.erb as a template source.

Please read the README.

Chef cookbooks do not use "Vagrant up" as a testing methodology. Please use
test-kitchen.

-s
