### ISSUE TITLE
Mysql installation on Vagrant hangs

### ISSUE THREAD

**Issue by endorama** [chef-cookbooks/mysql#326]
Hello everyone! I'm not able to use this cookbook due to it hanging the vagrant provision step.

No error is displayed, simply the process hangs.

Here you can find [the log](http://tny.cz/eb8dcf09).

This is my default recipe:

```ruby
#
# Cookbook Name:: cmysql
# Recipe:: default
#
# Copyright (c) 2015 The Authors, All Rights Reserved.

mysql_service 'default' do
  port '3306'
  version '5.6'
  initial_root_password 'change me'
  action [:create, :start]
end

mysql_config 'default' do
  # source 'my.cnf.erb'
  notifies :restart, 'mysql_service[default]'
  action :create
end

mysql_client 'default' do
  action :create
end
```

Any hint on how to solve this?

**Comment by someara** [comment]
I've added language to the README to address common usage questions. Let me know if this is still unclear.

**Comment by endorama** [comment]
Thanks for the feedback and your work!
