### ISSUE TITLE
tmpdir is hardcoded to /tmp

### ISSUE THREAD

**Issue by nkadel-skyhook** [chef-cookbooks/mysql#327]
The tmpdir for all MySQL instances is hardcoded to "/tmp", and doesn't seem to have any way to reset it. This is breaking down badly on VM's provisioned with modest "/" partitions, and generous "/var/lib/mysql-default" partitions configured precisely for the database.

Unfortunately, I'm not confident enough in rewriting the LWRP library functions to turn this into an attribute that is manageable for individual instances, or whether it should be a universal attribute.

**Comment by someara** [comment]
Hi Nico.

This falls under https://github.com/chef-cookbooks/mysql/issues/281
I'm planning on fixing that up in the next feature release.
Overriding it with an mysql_config resource is the best thing to do for now.

**Comment by someara** [comment]
#281
