### ISSUE TITLE
Release from 5.x branch to fix helper method pollution

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/mysql#328]
With the release of a new git cookbook yesterday, we're seeing a bunch of our cookbooks fail as described in https://github.com/jssjr/git/issues/56. For those of us still using the older 5.x releases of the mysql cookbook, would it be possible to release a new 5.x version with https://github.com/chef-cookbooks/mysql/commit/93d6467670a98fefc4471a2f082cd236c085eefa included?

We want to move to the newer mysql releases, but we'd like to keep working in the mean time, and pinning back every cookbook that might implement a similar method to the helpers here sounds like a whack-a-mole task :)

**Comment by someara** [comment]
Fixed in c2ab5b24a44a2109dc72f5b7125e3341bc29ec2a, released as 5.6.2

**Comment by martinb3** [comment]
Thanks!! Much appreciated!!

**Comment by martinb3** [comment]
Hmm, it seems `parsed_package_name` is still polluting other resources with 5.6.2 as released.

```
$ grep mysql Berksfile.lock
    mysql2_chef_gem (~> 1.0)
    mysql-multi (~> 1.4)
  mysql (5.6.2)
    yum-mysql-community (>= 0.0.0)
  mysql-multi (1.4.2)
    mysql (~> 5.0)
  mysql2_chef_gem (1.0.1)
    mysql (>= 0.0.0)
    mysql (>= 0.0.0)
    mysql (~> 5.0)
    mysql-multi (~> 1.0)
    mysql2_chef_gem (~> 1.0)
  yum-mysql-community (0.1.17)
```

```           ================================================================================
           Error executing action `install` on resource 'git_client[default]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `package_version' for Chef::Resource::YumPackage
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/mysql/libraries/resource_mysql_service.rb:59:in `parsed_package_version'
           /tmp/kitchen/cache/cookbooks/git/libraries/provider_git_client_package.rb:16:in `block (2 levels) in <class:Package>'
           /tmp/kitchen/cache/cookbooks/git/libraries/provider_git_client_package.rb:14:in `block in <class:Package>'      
```

From what I can tell, it looks like the fix wasn't applied to all possible methods that could have been polluting other resources, only methods in `MysqlCookbook::Helpers` were moved.

**Comment by patcon** [comment]
Hm. Hitting this as well
