### ISSUE TITLE
Issues when upgrading from version 5.x to 6.x on an already running node

### ISSUE THREAD

**Issue by mrdimka** [chef-cookbooks/mysql#330]
I have decided to upgrade my mysql DB server from using mysql cookbook  5.6.1 to 6.0.21.
When launching a new node(with no prior mysql configuration made be chef) then no problem is faced.
When I try to converge an already chef managed node with mysql configured by cookbook version older than 6(in my case 5.6.1) then I noticed the following issues:

1) Databases that have been created with previous cookbook version are not present. This happens because databases have been moved from /var/lib/mysql to /var/lib/mysql-default
2) service mysql stop/start/restart gives stop: Unknown instance:
3) Can not login back as mysql root user

Has anyone else faced the same issues in a similar situation?
What would the best approach to upgrade a node to the newest mysql cookbook version(6.x) while it's using an older version (5.x)?

**Comment by someara** [comment]
You'll have to manually point the new mysql_service instance to the old
data_dir by specifying that property on the resource.

When doing command line work with the mysql client, you'll need to either
point to the correct socket (the path has changed), or connect over the
network with -h

-s

**Comment by francescolaffi** [comment]
@someara is there a document about upgrading from v5 to v6?

Looked in the usuale places but I haven't found it, since there are breaking changes it would be useful to have some pointers.

**Comment by mrdimka** [comment]
@someara You are correct. I needed to set data_dir '/var/lib/mysql'
As far for point 2 of my initial message where service mysql start/stop/restart did not work the correct command is 
```bash
service mysql-default stop
```
I also found another issue
Let's say I provision a node for the first time having the following

```bash
mysql_service 'default' do
  port '3306'
  version '5.5'
  bind_address '127.0.0.1'
  data_dir '/var/lib/mysql'
  initial_root_password 'TestMePassword'
  action [:create, :start]
end
```
Then the root password is empty whatever I set on initial_root_password.
Only if I remove the line  data_dir '/var/lib/mysql' the password is set up with what I define in initial_root_password
As you can see we can not have the same cookbook for newly provisioned nodes and for nodes that come from older mysql cookbook version because of that.

**Comment by someara** [comment]
The 6.x mysql service resource shuts down any system service named "mysql".
The service name is now what you specify in the resource. In your case "mysql-default".

From the README, if you manually log into the machine and try to connect from the mysql command line client, you'l need to need to either a) specify a socket /var/lib/mysql-default with the -S flag, or b) connect over the network socket with -h.

If there is already data in /var/lib/mysql, no action will be taken to initialize the data_dir, or set a password. The password is whatever was set by the original 5.x installation.
