### ISSUE TITLE
Install on centos for mysql 5.7 fails

### ISSUE THREAD

**Issue by daften** [chef-cookbooks/mysql#337]
Because mysql_install_db --datadir=/var/lib/mysql-default --defaults-file=/etc/mysql-default/my.cnf has --defaults-file as last argument. It should be the first argument.
From mysql_install_db --help:
```
The following options may be given as the first argument:
--print-defaults        Print the program argument list and exit.
--no-defaults           Don't read default options from any option file,
                        except for login file.
--defaults-file=#       Only read default options from the given file #.
--defaults-extra-file=# Read this file after the global files are read.
```

**Comment by someara** [comment]
This is fixed in recent version of the cookbook.

https://github.com/chef-cookbooks/mysql/blob/master/libraries/helpers.rb#L111-L118

Just spot checked this in test-kitchen. Works like a charm..

-s
