### ISSUE TITLE
mysql_install_db is deprecated on some OS's

### ISSUE THREAD

**Issue by daften** [chef-cookbooks/mysql#338]
Error shown: mysql_install_db is deprecated. Please consider switching to mysqld --initialize

**Comment by someara** [comment]
I remember doing this at some point... where are you hitting this?
-s

**Comment by daften** [comment]
Thanks,
I'm working on CentOS 6.6 at this moment, trying to install mysql 5.7

**Comment by daften** [comment]
Interestingly, when #339 is fixed, this problem doesn't occure anymore it seems.

**Comment by someara** [comment]
This should be tied to mysql version, not OS version... investigating

**Comment by marcusl33beach** [comment]
Any progress on this? I am running into the same error on CentOS 6.6 with MySQL 5.7.

**Comment by someara** [comment]
Are you running the latest version of the cookbook?

https://github.com/chef-cookbooks/mysql/blob/df38fcfeea36eb99564284861082a0abd2e0e205/libraries/helpers.rb#L111-L118

I just verified the service56-single-centos-65 with test-kitchen. Worked fine.

**Comment by marcusl33beach** [comment]
Yes I just added 
```
cookbook 'mysql', '~> 6.0.22'
```
But looks like it is just a warning. So might  be able to ignore. 
```
2015-06-14T21:44:10.422672Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
```

**Comment by someara** [comment]
That's a different issue... closing this one
