### ISSUE TITLE
Add support for Ubuntu 15.04

### ISSUE THREAD

**Issue by jrosenboom** [chef-cookbooks/mysql#345]
There are several things that need to be fixed:

- Package definitions in `libraries/helpers.rb`
- Service provider needs to be Systemd instead of Upstart
- Systemd unit files live in `/lib/systemd/...` instead of `/usr/lib/systemd/...`
- Directory `/usr/libexec` does not exist by default

**Comment by jrosenboom** [comment]
@someara this is what I am using to run on Vivid, just would need some fixup to not break the Fedora/RHEL versions https://github.com/x-ion-de/mysql/tree/add-vivid-support

**Comment by someara** [comment]
Released in 6.0.31
