### ISSUE TITLE
mysql_service removes ability to connect with -h localhost (which is default)

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/mysql#346]
Whenever I use mysql_service to setup MySQL it seems that the resource is removing the root user with host "localhost".  Or something.

Regardless, the default package install supports connecting as root using either 127.0.0.1 or localhost and this cookbook removes that.

**Comment by flatrocks** [comment]
Apologies if this is the first thing you tried, but I'm responding to the "Or something."  

Have you specified the non-default socket created by recent versions of this cookbook? With default install on Ubuntu for example, this does not work:
```
mysql -u root -p<root_password>
```
But this does:
```
mysql -u root -p<root_password> --socket=/run/mysql-default/mysqld.sock
```
Lots of mysql applications including ```mysql``` command line tools assume the default socket unless it's specified explicitly.  The MySQL error message for this problem will be something like this:
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
``` 
If the root/localhost account really does not exist (or the password is wrong,) you should get this
```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```
(See #344)

**Comment by eric-tucker** [comment]
Yup.  That's the issue.  I observed this afterwards that I had to specify the socket path.  I suppose this can be marked as a duplicate of #344.
