### ISSUE TITLE
passwords MUST NOT be stored in attributes!

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/mysql#347]
Putting passwords into node attributes defies the whole purpose of using vault/encrypted data bags, because now the password is stored in plain text on the chef server!

**Comment by someara** [comment]
Agreed... which is why this cookbook doesn't require you to do that.

**Comment by someara** [comment]
What led you to create this issue? 
Are you using a very old version of the cookbook?
-s

**Comment by Sauraus** [comment]
Ah yes... 0.15 did things differently.

Would it be possible for the chef-percona cookbook to do adhere to semantic versioning rules? This would solve a lot of problems with cookbook pinning etc. as well.

**Comment by someara** [comment]
I don't see why not.

That project lives here: https://github.com/phlipper/chef-percona
