### ISSUE TITLE
Option to not modify default mysql service

### ISSUE THREAD

**Issue by jenssegers** [chef-cookbooks/mysql#348]
Is there an option to not modify the original mysql service (from default installation)? In my use case, I linked `/var/run/mysqld` to `/run/mysql-default` and `/etc/init.d/mysql` to `/etc/init.d/mysql-default` so that my applications can just interact with the default socket location.

But is there a way to disable the stop and disable actions on the default service? Because now, every time I run Chef the cookbook restarts the database. And if I remove `/etc/init.d/mysql`, the cookbook doesn't run at all.

**Comment by jenssegers** [comment]
A first step in solving this would be to check if the original system service file exists before trying to stop and disable it; see pull request #349.

**Comment by someara** [comment]
Sorry, this isn't going to work. Please use the TCP socket, or specify the path to the socket, either in your mysql_service resource, or in your application

**Comment by jenssegers** [comment]
Why not?

**Comment by someara** [comment]
Disabling the "system" service is a feature that lets multi-instance actually work.

See this thread for a longer explanation.

https://github.com/chef-cookbooks/mysql/issues/344

// @thommay

**Comment by jenssegers** [comment]
I'm not saying you should not disable the system service. The PR in #349 adds a check if the system service (init) exists, which makes sense to me? This allows me to just remove the original init file and be done with it.

**Comment by jenssegers** [comment]
It does not alter any of the existing behaviour. It just doesn't throw an error if the file isn't there.

**Comment by someara** [comment]
Sorry.. jumped the gun. Mis-groked the PR. Tried to re-open just now but the

On the surface it looks fine.. an extra sanity check (that the service providers should really be doing).

I guess I'm still a little confused about what this actually #349 actually accomplishes in relation to this issue.

**Comment by jenssegers** [comment]
It allows me to remove the system's original init.d file so that I do not start the original mysql service by accident.

**Comment by someara** [comment]
added these in 2b769351abd4a58f4a351d1301ffd542db45d6d1
