### ISSUE TITLE
Fully Configurable 

### ISSUE THREAD

**Issue by geleman** [chef-cookbooks/mysql#350]
I'm pretty new to chef, but not MySQL and I am looking to use this cookbook and from what I see and read this cookbook doesn't allow for configurations on all options. Am I wrong in this assumption? I'm looking at the default my.cnf and want to change every single option for the most part outside of port but I am not seeing where I can do this.

**Comment by someara** [comment]
A service's my.cnf does the minimum to get it running and loading more configs out of conf.d via an include.




Look under test/fixtures/cookbooks for examples of how to use the mysql_config resource to drop templates into the appropriate conf.d directory.



—

**Comment by geleman** [comment]
I understand the part about loading out of conf.d but I don't even want my.cnf file located in the place it is set up. With my organization we do a different file structure and would like to be able to fully customize the instance. This includes datadir and logs on separate mounts/partitions and tmpdir  mounted in memory on a separate tmpfs disk not /dev/shm/. I like what I have been able to do thus far but the ability to not be able to fully customize might be killer for me and I'm to green on chef to write a cookbook from scratch that does the install at this point.

**Comment by someara** [comment]
You have full control of The mysql_service resource only owns a few lines, data_dir being one of them.



—

**Comment by geleman** [comment]
Also I did see where I can create a foo.erb files for configs in the test location but I would need to override your defaults with these settings, but that still leaves me with the my.cnf and conf.d in a location I do not perfer. The datadir is a very important options for me to be able to control.

**Comment by someara** [comment]
Er, sorry. iPhone. 




You have full control of every line.




The mysql_service resource owns my.cnf, and will let you configure data_dir, listen_port, and a few others, listed in the readme.




Anything beyond that goes in a mysql_config template source.




-s






—

**Comment by geleman** [comment]
I guess I'm not seeing where I can change the ones in the README. I have been going through everything and just not seeing how I can do it. Granted like I said before I am a complete newb to chef but I'm not seeing where I can change the default/variable values.

**Comment by someara** [comment]
Look at test/fixtures/mysql_service_test/recipes/multi.rb









—

**Comment by geleman** [comment]
I guess I just have a lot things to figure out because that doesn't help me a whole lot. It's probably just my lack of knowledge in chef.

**Comment by geleman** [comment]
So I think I have finally got things figured out but have run into an issue. I read the multi.rb and see how i can hard code in such things as data_dir. So I'm trying to hard code the error_log location and it fails. I'm going to attempt to move tmp and try some others. The main ones i'm concerned with though are logs directory, data directory and tmp dir. Is the error_log use not correct by using it under service like data_dir?
