### ISSUE TITLE
Chef 12.4.0 update breaks on Centos 6.6

### ISSUE THREAD

**Issue by geleman** [chef-cookbooks/mysql#359]
================================================================================
==> mysql1: Error executing action `create` on resource 'mysql_service[test]'
==> mysql1: ================================================================================
==> mysql1:
==> mysql1:
==> mysql1: NameError
==> mysql1: ---------
==> mysql1: No resource, method, or local variable named `create_stop_system_service' for `Chef::Provider::MysqlService ""'
==> mysql1:
==> mysql1:
==> mysql1: Cookbook Trace:
==> mysql1: ---------------
==> mysql1: /tmp/vagrant-chef/b34efc1fc708cc5c747dd326d5d65de9/cookbooks/mysql/libraries/provider_mysql_service.rb:39:in `block in <class:MysqlService>'

**Comment by nickma** [comment]
Same here:
7) had an error: NameError: No resource, method, or local variable named `create_stop_system_service' for `Chef::Provider::MysqlService ""'
==> default: [2015-06-24T21:34:08+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by someara** [comment]
@lamont-granquist @jkeiser any idea why this would have broken as of 12.4?

**Comment by lamont-granquist** [comment]
Probably the same issue as the httpd cookbook.  You should make sure that sysvinit is only provided for rhel < 7.0 and systemd is only provided for rhel >= 7.0, then chef-client doesn't have to guess.

**Comment by someara** [comment]
I'll fix this up when the dust settles over in httpd

On Thu, Jun 25, 2015 at 10:51 PM, Lamont Granquist <notifications@github.com

**Comment by lamont-granquist** [comment]
I'm working on a PR for this cookbook as well.

**Comment by jkeiser** [comment]
This is getting fixed in 12.4.1, correct?  The cookbook should get less ambiguous too, obviously.

**Comment by lamont-granquist** [comment]
Yes, fix all the things.

**Comment by Dreeg** [comment]
When will it be released?

**Comment by jrosenboom** [comment]
So is there a workaround for this other than sticking to <12.4.0?

**Comment by someara** [comment]
Pin to < 12.4.0 for now... fix up similar to httpd is on the way

**Comment by someara** [comment]
Fixed in chef-client 12.4.1 and mysql 6.0.28
