### ISSUE TITLE
Latest release (6.0.25) broken on CentOS in Docker

### ISSUE THREAD

**Issue by joerg** [chef-cookbooks/mysql#365]
There seems be a bug/feature/strangeness in Chef regarding the service_resource_providers selection which breaks the latest release on CentOS 6.6 running in Docker. I just tested my cookbook (which worked yesterday with the 6.0.24 release) with kitchen-docker_cli which throws this:
```
================================================================================
    Error executing action `start` on resource 'mysql_service[atlassian]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    service[atlassian :start mysql-atlassian] (/tmp/kitchen/cache/cookbooks/mysql/libraries/provider_mysql_service_upstart.rb line 41) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/start mysql-atlassian ----
    STDOUT: 
    STDERR: start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
    ---- End output of /sbin/start mysql-atlassian ----
    Ran /sbin/start mysql-atlassian returned 1
    
    Resource Declaration:
    ---------------------
    # In /tmp/kitchen/cache/cookbooks/atlassian-database/recipes/mysql.rb
    
     62: mysql_service settings['instance'] do
     63:   action :start
     64: end
```

Of course using upstart on CentOS does not work. The chef-shell reveals the problem (latest release 6.0.25 checks if :upstart is included):
```
chef > Chef::Platform::ServiceHelpers.service_resource_providers
 => [:upstart, :redhat] 
```

I am also gonna forward this to the chef bugtracker. Maybe they will fix it, but for sure a fix in this cookbook would be a lot easier and faster. Maybe just check if it includes :upstart and not :redhat (ugly but it would fix the problem)

EDIT: I just learned that CentOS 6.6 comes with upstart installed, so this does not seem to be a Chef bug.

**Comment by someara** [comment]
Hello!

This was fixed up in 12.4.1. Also the cookbook =)
