### ISSUE TITLE
tmp_dir don't work in mysql_service block

### ISSUE THREAD

**Issue by fakhruddinhamid** [chef-cookbooks/mysql#371]
I tried using tmp_dir method in mysql_service block to change the default tmpdir location but got an error while running recipe

tmp_dir : no such method

I found a work around by over writing this variable in one of cnf files in conf.d/ dir.

**Comment by tas50** [comment]
@fakhruddinhamid Can you give us an example of the Chef code you're trying to run and the exact error message that came back?

**Comment by fakhruddinhamid** [comment]
@tas50 This was way long back I don't remember this now.
Some info I could provide though, I was trying to have a separate tmp dir some thing like /data/tmp as we are on EBS volumes and bigger ones are faster, the error was in relation to setting up a tmp dir instead of default which is /tmp

**Comment by iennae** [comment]
If you happen to remember this it would be helpful if you updated this and reopened. As it hasn't been requested since you initially filed I'm going to go ahead and close this for now.
