### ISSUE TITLE
my_extra_settings not getting created in the right dir?

### ISSUE THREAD

**Issue by mauriceteunissen** [chef-cookbooks/mysql#374]
I'm using v6.1.0 of the cookbook, from the chef supermarket, on ubuntu 14.04. Here is my default.rb wrapper:

    mysql_service 'listbuilder' do
      port '3306'
      version '5.6'
      initial_root_password 'myrootpass'
      action [:create, :start]
    end
    
    mysql_config 'listbuilder' do
      source 'my_extra_settings.erb'
      notifies :restart, 'mysql_service[listbuilder]'
      action :create
    end

This is generating a /etc/mysql-listbuilder/my.cnf file that includes this line which looks correct:

    !includedir /etc/mysql-listbuilder/conf.d

However, the mysql_config block is creating my extra settings cnf file in /etc/mysql-default/conf.d/, as seen in the chef output below:

     * mysql_config[listbuilder] action create
    (up to date)
       * user[listbuilder :create mysql] action create (up to date)
       * directory[listbuilder :create /etc/mysql-default/conf.d] action create
         - create new directory /etc/mysql-default/conf.d
         - change mode from '' to '0750'
         - change owner from '' to 'mysql'
         - change group from '' to 'mysql'
       * template[listbuilder :create /etc/mysql-default/conf.d/listbuilder.cnf] action create
         - create new file /etc/mysql-default/conf.d/listbuilder.cnf
         - update content in file /etc/mysql-default/conf.d/listbuilder.cnf from none to 967ba6
         --- /etc/mysql-default/conf.d/listbuilder.cnf      2015-08-05 23:45:04.608792526 +0000

Shouldn't it be creating that config file in /etc/mysql-listbuilder/conf.d instead of /etc/mysql-default/conf.d? so that the !includedir element in /etc/mysql-lisbuilder/my.cnf can find it, or am I missing something?

**Comment by someara** [comment]
You need to specify "instance 'listbuilder'" property on your mysql_config resource
