### ISSUE TITLE
On Debian 8 default MySQL service is not disabled

### ISSUE THREAD

**Issue by ovaistariq** [chef-cookbooks/mysql#378]
The cookbook sets up multiple MySQL instances on the same machine, therefore the services are named as mysql-<some_instance_name>. For this to work after installing the MySQL packages default service should be disabled, otherwise restarting the machine causes the default "mysql" service to start and the service created using the cookbook fails to start up.

Here is a list of services after the reboot:

```
root@ip-10-10-0-245:~# systemctl list-units | grep mysql
● mysql-default.service                            loaded failed failed    mysql_service[mysql-default]
  mysql.service                                    loaded active running   LSB: Start and stop the mysql database server daemon
```

As you can see the default mysql service is running. The MySQL service was setup as follows:

``` ruby
mysql_service node["mysql"]["service_name"] do
  version node["mysql"]["version"]
  initial_root_password node["mysql"]["root_password"]
  socket node["mysql"]["socket"]
  action [:create, :start]
end
```

The cookbook that is using the mysql cookbook to create a service can be checkout here:
https://github.com/twindb/twindb-agent-testing/tree/master/test/fixtures/cookbooks/mysql_server_client_test

The fix is to disable the default service after installing the packages.

**Comment by someara** [comment]
Indeed, that's what the cookbook is trying to do

https://github.com/chef-cookbooks/mysql/blob/master/libraries/provider_mysql_service_base.rb#L38

It is obviously failing to do so.

I'll take a crack at tracking it down when I have a moment later this week

**Comment by ovaistariq** [comment]
Yeah its funny then, I had to explicitly disable the service:
https://github.com/twindb/twindb-agent-testing/commit/a90d2c39f4ef083e512b53a965b8b128c6e2a18d

**Comment by cheeseplus** [comment]
This should be fixed in current versions but if not please open a new issue with version details.
