### ISSUE TITLE
ServerSpec Looking for Files that Associated Resource Doesn't Create

### ISSUE THREAD

**Issue by jcderose** [chef-cookbooks/mysql#396]
The ServerSpec script mysql/test/integration/config55/serverspec/linux_spec.rb suggests the directory `/etc/mysql-default` should be as follows:

```
  describe file("#{prefix_dir}/etc/mysql-default") do
    it { should be_directory }
    it { should be_mode 755 }
    it { should be_owned_by 'root' }
    it { should be_grouped_into 'root' }
  end
```

However, in a generic/default setup, this is not the case. The default resource of:

```
mysql_client 'default' do
  action :create
end

mysql_service 'default' do
  version '5.5'
  initial_root_password 'my-password'
  action [:create, :start]
end
```

Yields this:

```
vagrant@vm:~$ ls -l /etc/ | grep mysql
drwxr-xr-x 3 root  root    4096 Jan  5 14:35 mysql
drwxr-x--- 3 mysql mysql   4096 Jan  5 14:35 mysql-default
```

Should the `/etc/mysql-default` directory be `chown`-ed to root:root with permissions 755 or should the ServerSpec test be updated to mysql:mysql with permissions 750?

**Comment by iennae** [comment]
Thanks for reporting this issue @jcderose. I believe this has been removed at this point. If it's still an issue, please do re-open.
