### ISSUE TITLE
Mysql 5.5 login failed

### ISSUE THREAD

**Issue by sernapallyanurag** [chef-cookbooks/mysql#401]
mysql_service 'sonar' do
  port '3306'
  version '5.5'
  initial_root_password 'root'
  action [:create, :start]
end

root@xyz:~# mysql -S /var/run/mysql-sonar/mysqld.sock -u mysql -p
Enter password: <root>
ERROR 1045 (28000): Access denied for user 'mysql'@'localhost' (using password:
YES)
root@xyz:~# mysql -S /var/run/mysql-sonar/mysqld.sock -u root -p
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: Y
ES)

**Comment by nkadel-skyhook** [comment]
The LWRP does not publish its socket in a legible location: It's hidden inside /etc/mysql-default/, which does not support the default /etc/my.cnf location so useful to single MySQL instances.

Try putting the socket in your working $HOME/.my.cnf file, or using "--protocol=tcp" in your command line to test the hypothesis.

**Comment by AneudyM** [comment]
For some weird reason I am also having issues of that nature. The cookbook seems to not be assigning the 'initial_root_password' that I am specifying in the mysql_service directive. It bugs me because it was working last night, and today it stopped. I rolled back any changes I made, and it keeps not assigning the initial root password.

**Comment by sernapallyanurag** [comment]
@AneudyM  can you present your problem with more details.

**Comment by AneudyM** [comment]
Well, there's only so much I can show, it is basically the same as yours. I have this in my recipe:

```
root_pass = 'my_password'
mysql_service 'local' do
        port '3306'
        initial_root_password root_pass
        action [ :create, :start ]
end
```
After performing a chef-client run on the node, I try login into the mysql service with root user and password I assigned above and I get the following:

```
mysql -u root -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

But when I try `mysql -u root` without a password, then it logs me in, which means that no password was even assigned to the service.

**Comment by AneudyM** [comment]
@sernapallyanurag, I think I figured out what the issue in my case was. It had to do with AppArmor. Do the following and see if that works for you:

```
sudo apt-get remove --purge mysql*
sudo apt-get autoremove
sudo apt-get clean
sudo rm -rf `locate mysql`
sudo apt-get remove --purge apparmor
```
Now do your `sudo chef-client` and see how that works for you. I am using a VirtualBox node with Ubuntu Server 14.04 LTS installed.
