### ISSUE TITLE
Mysql doesnot start even after turning off selinux

### ISSUE THREAD

**Issue by sernapallyanurag** [chef-cookbooks/mysql#408]
```
============================================================================
```
# 

```
Error executing action `start` on resource 'mysql_service[default]'
============================================================================
```
# 

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
service[default :start mysql-default] (/var/chef/cache/cookbooks/mysql/libra
```

ries/provider_mysql_service_sysvinit.rb line 26) had an error: Mixlib::ShellOut:
:ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/service mysql-default start ----
    STDOUT: Starting mysql-default (via systemctl):  [FAILED]
    STDERR: Job for mysql-default.service failed. See 'systemctl status mysql-de
fault.service' and 'journalctl -xn' for details.
    ---- End output of /sbin/service mysql-default start ----
    Ran /sbin/service mysql-default start returned 1

I am using Centos 7.1 in azure and SElinux is disabled still I get this error
Mysql cookbook v6.0.22
OS: Centos 7.1 openlogic azure Image

recipe:
mysql_service 'default' do
  port '3306'
  version '5.6'
  initial_root_password 'root'
  provider Chef::Provider::MysqlService::Sysvinit
  action :create
end

mysql_service 'default' do
  action :start
end

**Comment by sernapallyanurag** [comment]
**systemctl status mysql-default output
**
mysql-default.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/rc.d/init.d/mysql-default)
   Active: failed (Result: exit-code) since Fri 2016-03-11 08:22:52 UTC; 4min 1s
 ago
  Process: 7095 ExecStart=/etc/rc.d/init.d/mysql-default start (code=exited, sta
tus=1/FAILURE)

Mar 11 08:22:22 testscript mysql-default[7095]: Starting MySQL instance mysq...t

Mar 11 08:22:52 testscript mysql-default[7095]: Starting mysql-default:  [FA...]

Mar 11 08:22:52 testscript systemd[1]: mysql-default.service: control proce...=1

Mar 11 08:22:52 testscript systemd[1]: Failed to start LSB: Start and stop ...n.

Mar 11 08:22:52 testscript systemd[1]: Unit mysql-default.service entered f...e.

Hint: Some lines were ellipsized, use -l to show in full.

**Comment by AjeetK** [comment]
Try to run `sestatus` command and if it shows disable then try to enable it with command `setenforce 1`. More details can be found [here](http://jee-appy.blogspot.com/2017/01/mysql-start-returned-3-chef.html)

**Comment by cheeseplus** [comment]
It looks like you're trying to force the provider to be sysinit when it should be systemd for CentOS7 - this really isn't a bug as such. Feel free to open a new issue against current versions if you're still having issues on CentOS 7.

**Comment by EdwardHerbert** [comment]
This is still an ongoing issue.
