### ISSUE TITLE
Unable to install mysql on ubuntu 14.04

### ISSUE THREAD

**Issue by sernapallyanurag** [chef-cookbooks/mysql#419]
Cookbook version - 6.1.3
Chef-client version- 12.9.38

 Platform Details - Ubuntu 14.04 running on Microsoft azure
 Scenario:
I am trying t0 install Mysql 5.5 as one of the requirements for sonarqube

Steps to Reproduce: My recipe
``
mysql_service 'default' do
  port '3306'
  version '5.5'
  initial_root_password 'root'
  end

mysql_service 'default' do
  action :start
end
``
Expected Result:
Installation of Mysql with default root user.

 Actual Result:
``
    * bash[default :create initial records] action run

      ================================================================================
      Error executing action `run` on resource 'bash[default :create initial records]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0, 1, 2], but received '127'
      ---- Begin output of "bash"  "/tmp/chef-script20160419-2339-qutf92" ----
      STDOUT:
      STDERR: /tmp/chef-script20160419-2339-qutf92: line 18: warning: here-document at line 6 delimited by end-of-file (wanted `EOSQL')
      cat: /run/mysql-default/mysqld.pid: No such file or directory
      /tmp/chef-script20160419-2339-qutf92: line 6: DELETE: command not found
      ---- End output of "bash"  "/tmp/chef-script20160419-2339-qutf92" ----
      Ran "bash"  "/tmp/chef-script20160419-2339-qutf92" returned 127

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_base.rb

      145:         bash "#{new_resource.name} :create initial records" do
      146:           code init_records_script
      147:           returns [0, 1, 2] # facepalm
      148:           not_if "/usr/bin/test -f #{parsed_data_dir}/mysql/user.frm"
      149:           action :run
      150:         end
      151:       end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_base.rb:145:in `block in <class:MysqlServiceBase>'

      bash("default :create initial records") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        command "default :create initial records"
        backup 5
        returns [0, 1, 2]
        code "        set -e\n        rm -rf /tmp/mysql-default\n        mkdir /tmp/mysql-default\n\n        cat > /tmp/
mysql-default/my.sql \n\t\t<<-EOSQL DELETE FROM mysql.user ; \n\t\tCREATE USER 'root'@'%' IDENTIFIED BY 'root' ; \n\t\tG
RANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ; \n\t\tFLUSH PRIVILEGES; DROP DATABASE IF EXISTS test ; \n\t\tEOSQL \n\
n       mysql_install_db --defaults-file=/etc/mysql-default/my.cnf --datadir=/var/lib/mysql-default\n       /usr/bin/mys
qld_safe --defaults-file=/etc/mysql-default/my.cnf --init-file=/tmp/mysql-default/my.sql &\n\n       while [ ! -f /run/m
ysql-default/mysqld.pid ] ; do sleep 1 ; done\n       kill `cat /run/mysql-default/mysqld.pid`\n       while [ -f /run/m
ysql-default/mysqld.pid ] ; do sleep 1 ; done\n       rm -rf /tmp/mysql-default\n"
        interpreter "bash"
        declared_type :bash
        cookbook_name "mysql"
        not_if "/usr/bin/test -f /var/lib/mysql-default/mysql/user.frm"
      end

      Platform:
      ---------
      x86_64-linux

    ================================================================================
    Error executing action `create` on resource 'mysql_service[default]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    bash[default :create initial records] (/var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_base.rb line
 145) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 1, 2], but received '127'
    ---- Begin output of "bash"  "/tmp/chef-script20160419-2339-qutf92" ----
    STDOUT:
    STDERR: /tmp/chef-script20160419-2339-qutf92: line 18: warning: here-document at line 6 delimited by end-of-file (wanted `EOSQL')
    cat: /run/mysql-default/mysqld.pid: No such file or directory
    /tmp/chef-script20160419-2339-qutf92: line 6: DELETE: command not found
    ---- End output of "bash"  "/tmp/chef-script20160419-2339-qutf92" ----
    Ran "bash"  "/tmp/chef-script20160419-2339-qutf92" returned 127

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/mysql/recipes/default.rb

      1: mysql_service 'default' do
      2:   port '3306'
      3:   version '5.5'
      4:   initial_root_password 'root'
      5:   end
      6:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/mysql/recipes/default.rb:1:in `from_file'

    mysql_service("default") do
      action [:create]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :mysql_service
      cookbook_name "mysql"
      recipe_name "default"
      port "3306"
      version "5.5"
      initial_root_password "root"
      instance "default"
      run_user "mysql"
      run_group "mysql"
      charset "utf8"
    end

    Platform:
    ---------
    x86_64-linux

Running handlers:
[2016-04-19T14:21:38+00:00] ERROR: Running exception handlers
[2016-04-19T14:21:38+00:00] ERROR: Creating JSON exception report
  - Chef::Handler::JsonFile
Running handlers complete
[2016-04-19T14:21:38+00:00] ERROR: Exception handlers complete
Chef Client failed. 37 resources updated in 09 minutes 23 seconds
[2016-04-19T14:21:39+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-04-19T14:21:39+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-04-19T14:21:39+00:00] ERROR: mysql_service[default] (mysql::default line 1) had an error: Mixlib::ShellOut::ShellC
ommandFailed: bash[default :create initial records] (/var/chef/cache/cookbooks/mysql/libraries/provider_mysql_service_ba
se.rb line 145) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 1, 2], but receive
d '127'
---- Begin output of "bash"  "/tmp/chef-script20160419-2339-qutf92" ----
STDOUT:
STDERR: /tmp/chef-script20160419-2339-qutf92: line 18: warning: here-document at line 6 delimited by end-of-file (wanted
 `EOSQL')
cat: /run/mysql-default/mysqld.pid: No such file or directory
/tmp/chef-script20160419-2339-qutf92: line 6: DELETE: command not found
---- End output of "bash"  "/tmp/chef-script20160419-2339-qutf92" ----
Ran "bash"  "/tmp/chef-script20160419-2339-qutf92" returned 127
[2016-04-19T14:21:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit co
de 1)
``

**Comment by tas50** [comment]
There's been a lot of changes to the version logic.  Can you give this a try on the 7.X release and let me know if you're still having issues.  I'm going to close it for now, but feel free to open it back up.
