### ISSUE TITLE
How do I add max_allowed_packet size to mysql?

### ISSUE THREAD

**Issue by sernapallyanurag** [chef-cookbooks/mysql#423]
### Cookbook version

mysql 6.1.2
### Chef-client version

12.11.18
### Platform Details

[CentOS 7.1 open logic Azure VM]
### Scenario:

I am trying to configure mysql for bugzilla. How can I include
 `max_allowed_packet=4M`
### Steps to Reproduce:

can this be achieved using 
`mysql_config` ?? 
### Expected Result:

`max_allowed_packet=4M`

**Comment by gxof** [comment]
Hello, 

I would like to ask the same question. Is there a way to add max_allowed_packet?

Thanks

**Comment by iennae** [comment]
You can use mysql_config and supply a template or supply the configuration to the mysql_service resource mysqld_options parameter.

Example:
mysql_service 'foo' do
  port '3306'
  version '5.7'
  mysqld_options ({ max_allowed_packet: '4M' })
  initial_root_password 'potato'
  action [:create, :start]
end
