### ISSUE TITLE
How to apply usage in metadata.rb file?

### ISSUE THREAD

**Issue by sumimathew** [chef-cookbooks/mysql#431]
### Cookbook version

7.0.1
### Platform Details

RHEL
### Scenario:

i am trying to install mysql  7.0.1 but  it showed " compile error".I also  tried  to get the metadata.rb file within the cookbook but not found.then how to apply usage.
### Steps to Reproduce:

just download and extracted mysql cookbook
### Expected Result:

installed successfully
### Actual Result:

compile error

**Comment by cheeseplus** [comment]
If still having problems, please open a new issue with complete stacktrace. Closing given lack of detail and age.
