### ISSUE TITLE
Version '5.6.30-0ubuntu0.14.04.1' for 'mysql-server-5.6' was not found

### ISSUE THREAD

**Issue by theonedemon** [chef-cookbooks/mysql#435]
### Cookbook version
8.0.1

### Chef-client version
12.10.24

### Platform Details
atlas: ubuntu/trusty64 (virtualbox, 20160714.0.0)
Vagrant: 1.8.1
Vagrant plugin: vagrant-omnibus (1.4.1)

### Scenario:

#node:

"run_list": [
		"recipe[apt]",
		"recipe[app]"
	],
"mysql": {
		"version": "5.6",
		"remove_anonymous_users": true,
		"remove_test_database": true,
		"bind_address": "0.0.0.0",
		"allow_remote_root": false,
		"server_root_password": "test"
	},

# In cookbook "app": 
mysql_service 'default' do
	port '3306'
	version node['mysql']['version']
	bind_address node['mysql']['bind_address']
	initial_root_password node['mysql']['server_root_password']
	action [:create, :start]
end

# Cheffile.lock :
apt (4.0.1)
mysql (8.0.1)

### Steps to Reproduce:
vagrant provider

### Expected Result:
Install mysql-server-5.6

### Actual Result:
==> default: [2016-07-22T11:03:12+03:00] ERROR: mysql_service[default] (app::default line 214) had an error: Mixlib::ShellOut::ShellCommandFailed: mysql_server_installation_package[default] (/tmp/vagrant-chef/3d0267c78fb353a2a79c902de75c4fab/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[mysql-server-5.6] (/tmp/vagrant-chef/3d0267c78fb353a2a79c902de75c4fab/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
==> default: ---- Begin output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
==> default: STDOUT: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: STDERR: E: Version '5.6.30-0ubuntu0.14.04.1' for 'mysql-server-5.6' was not found
==> default: ---- End output of apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 ----
==> default: Ran apt-get -q -y install mysql-server-5.6=5.6.30-0ubuntu0.14.04.1 returned 100
==> default: [2016-07-22T11:03:12+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

### .chef/cookbooks/mysql/libraries/helpers.rb :

      return '5.5.49-0ubuntu0.12.04.1' if major_version == '5.5' && precise?
      return '5.5.49-0ubuntu0.14.04.1' if major_version == '5.5' && trusty?
      return '5.6.30-0ubuntu0.14.04.1' if major_version == '5.6' && trusty?
      return '5.7.12-0ubuntu1.1' if major_version == '5.7' && xenial?

## apt-cache policy mysql-server-5.6 : 
mysql-server-5.6:
  Installed: (none)
  Candidate: 5.6.31-0ubuntu0.14.04.2
  Version table:
     5.6.31-0ubuntu0.14.04.2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/universe amd64 Packages
     5.6.16-1~exp1 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

**Comment by theonedemon** [comment]
my mistake, I found the option: package_version

**Comment by ezekg** [comment]
@theonedemon, how did you solve this? What did you set as your `package_version` option?

**Comment by theonedemon** [comment]
add option: package_version: "5.6.31-0ubuntu0.14.04.2"
and cookbook mysql 8.0.1 not work, downgrade to 7.2.0
