### ISSUE TITLE
cannot install on ubuntu 16.04.1

### ISSUE THREAD

**Issue by ahrib** [chef-cookbooks/mysql#447]
### Cookbook version
8.0.1

### Chef-client version
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2

### Platform Details
ubuntu 16.04.1
vagrant

vagrant@default-ubuntu-1604:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

kitchen.yml reads 
platforms:
  - name: ubuntu-16.04

### Scenario:
install mysql-server on ubuntu

### Steps to Reproduce:
mysql_service 'default' do
  version '5.7'
  action [:create, :start]
end

### Expected Result:
install sys default currently at 5.7.13-0ubuntu0.16.04.2

### Actual Result:
---- Begin output of apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 ----
       STDOUT: Reading package lists...
       Building dependency tree...
       Reading state information...
       STDERR: E: Version '5.7.12-0ubuntu1.1' for 'mysql-server-5.7' was not found
       ---- End output of apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 ----
       Ran apt-get -q -y install mysql-server-5.7=5.7.12-0ubuntu1.1 returned 100

**Comment by ahrib** [comment]
possibly dupe of 
Incorrect default package versions #439

**Comment by someara** [comment]
Fixed up in 8.0.2
