### ISSUE TITLE
parameter package_name not working correctly

### ISSUE THREAD

**Issue by ahrib** [chef-cookbooks/mysql#448]
### Cookbook version

8.0.1
### Chef-client version

Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2
### Platform Details

ubuntu 16.04.1
vagrant

vagrant@default-ubuntu-1604:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.1 LTS
Release: 16.04
Codename: xenial

kitchen.yml reads 
platforms:
- name: ubuntu-16.04
### Scenario:

install mysql using the official repo by specifying the package_name "mysql-server"
### Steps to Reproduce:

apt_repository 'mysql' do
  uri 'http://repo.mysql.com/apt/ubuntu/'
  key 'http://repo.mysql.com/RPM-GPG-KEY-mysql'
  distribution node['lsb']['codename']
  components ['mysql-5.7', 'mysql-tools']
  deb_src true
end

mysql_service 'default' do
  version '5.7'
  package_name 'mysql-server'
  action [:create, :start]
end
### Expected Result:

expect recipe to perform an "apt-get install mysql-server"
### Actual Result:

recipe runs "apt-get install mysql-server-5.7"
i.e. package_name above is not honored

**Comment by cheeseplus** [comment]
We've dropped the hardcodes in 8.1+ so closing this but please open a new issue if still present.
