### ISSUE TITLE
On Debian 7 is wrong package version?

### ISSUE THREAD

**Issue by netmaniac** [chef-cookbooks/mysql#456]
### Cookbook version
8.0.1

### Chef-client version
12.13.37

### Platform Details
bentoo/debian-7.9 on VirtualBox

### Scenario:
Trying to install simple webapp

During install mysql client service:
     STDERR: E: Version '5.5.49-0+deb7u1' for 'mysql-client-5.5' was not found
       ---- End output of apt-get -q -y install mysql-client-5.5=5.5.49-0+deb7u1 ----
       Ran apt-get -q -y install mysql-client-5.5=5.5.49-0+deb7u1 returned 100

According to https://packages.qa.debian.org/m/mysql-5.5.html 5.5.49 is only available for deb8u1. Adding   package_version '5.5.50-0+deb7u2' to service definition solves problem. It looks like this version should be returned by helper: https://github.com/chef-cookbooks/mysql/blob/master/libraries/helpers.rb#L177

**Comment by someara** [comment]
Fixed up in 8.0.2
