### ISSUE TITLE
Does not install libmysqlclient-dev

### ISSUE THREAD

**Issue by greneholt** [chef-cookbooks/mysql#457]
### Cookbook version

8.0.1
### Chef-client version

12.13.37
### Platform Details

Ubuntu 14.04
### Scenario:

Install the mysql gem, which requires the mysql client dev libraries to be installed.
### Steps to Reproduce:

In a recipe, insert the following:

```
mysql_client 'default' do
  version '5.6'
  package_version ''
  action [:create]
end
```
### Expected Result:

I expected the development libraries to be installed.

From the cookbook description: The mysql_client resource manages the MySQL client binaries and **development libraries.**
### Actual Result:

The development libraries were not installed. On Ubuntu 14.04, libmysqlclient-dev was not installed.

As best as I can tell, the development library packages were removed in commit 824e854a1260c02800304a23c7d34efa8a627672.

**Comment by patcon** [comment]
My options when encountered this are either to:
1. pin back mysql coobkook with `< 8`
2. add a compile-time install of `libmysqlclient-dev` before the `mysql2_chef_gem` resource

**Comment by rmyates** [comment]
I've just hit this too, looks to be a breaking change that perhaps was missed during refactoring.

I've also noticed following the Readme that passing an array of packages to package_name in mysql_client resource breaks:
`Property package_name must be one of: String!  You passed ["mysql-client", "libmysqlclient-dev"]`

**Comment by geleman** [comment]
This is a continuing breaking change and needs to be addressed either here or in mysql2_chef_gem.

**Comment by javornikolov** [comment]
I'm facing that problem on CentOS. I can imagine two options here:
 1. fix the documentation - make it clear `mysql_client` doesn't pull development libraries. In such case it makes sense to add another recipe e.g. `mysql_devel` which to do that.
 2. add back the development libraries to be installed by `mysql_client`.

Reviewing the release notes - option (2) looks more appropriate at first glimpse, at least for `8.x`. If finer granularity is needed - it may be achieved e.g. by adding `include_devel_libraries | default=true)` option and a separate `mysql_devel` recipe.

**Comment by tas50** [comment]
This was fixed in the last release.
