### ISSUE TITLE
Create database using attributes

### ISSUE THREAD

**Issue by AnselmoPfeifer** [chef-cookbooks/mysql#458]
### Cookbook version

5.3.6
### Chef-client version

chef-solo -v
Chef: 11.16.4
### Platform Details

Ubuntu 14.04
### Scenario:

I can create database using attributes? 
how would?
### Steps to Reproduce:

if node['mysql']['databases']
  server_root_password = node['mysql']['server_root_password']
  node['mysql']['databases'].each do | name |
    bash 'create_database' do
      code <<-EOF
      sudo echo -e "create database #{name};" | /usr/bin/mysql -u root '-p#{server_root_password}'
      EOF
    end
  end
end
### Expected Result:

STDERR: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-e create database {"name"=>"testebadabase", "password"=>"TesteqhYgdhcg66EPg3uk"}' at line 1

**Comment by cheeseplus** [comment]
As of version 6, the cookbook became a library cookbook and no longer uses any attributes. We're now 8.2.0 and chef-client 11 is no longer supported. If you have issues with a recent version, please feel free to open an issue.
