### ISSUE TITLE
No candidate version available for mysql-community-server on CentOS 6.8

### ISSUE THREAD

**Issue by free0ldman** [chef-cookbooks/mysql#470]
### Cookbook version
8.0.2

### Chef-client version
12.13.30

### Platform Details
CentOS 6.8 

### Scenario:
In my recipe, I was trying to do a simple install and start of MySQL service, code as below:

`mysql_service 'default' do
    port '3306'
    version '5.6'
    bind_address '0.0.0.0'
    initial_root_password 'MyPass'
    action [:create, :start]
end`

### Steps to Reproduce:
Using above codes

### Expected Result:
MySQL gets installed and started.

### Actual Result:
Error shows no candidate for mysql-community-server was found:

 * mysql_service[test] action create
    * mysql_server_installation_package[test] action install
      * yum_package[mysql-community-server] action install
        * No candidate version available for mysql-community-server
        ================================================================================
        Error executing action `install` on resource 'yum_package[mysql-community-server]'
        ================================================================================

        Chef::Exceptions::Package
        -------------------------
        No candidate version available for mysql-community-server

        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb

         17:       package package_name do
         18:         version package_version if package_version
         19:         options package_options if package_options
         20:         notifies :install, 'package[perl-Sys-Hostname-Long]', :immediately if platform_family?('suse')
         21:         notifies :run, 'execute[Initial DB setup script]', :immediately if platform_family?('suse')
         22:         action :install
         23:       end
         24:

        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb:17:in `block in <class:MysqlServerInstallationPackage>'

        yum_package("mysql-community-server") do
          package_name "mysql-community-server"
          action [:install]
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          declared_type :package
          cookbook_name "MyCookbook"
          flush_cache {:before=>false, :after=>false}
          version "5.6.29-2.el6"
        end

        Platform:
        ---------
        x86_64-linux

**Comment by michaelnico** [comment]
I got the same issue here.

### Cookbook version
8.0.2
### Chef-client version

12.13.37

### Platform Details
CentOS 6.7

### Recipe
I used the sample recipe in `mysql` cookbook documentation.

```ruby
mysql_service 'foo' do
  port '3306'
  version '5.5'
  initial_root_password 'changeme'
  action [:create, :start]
end

mysql_config 'foo' do
  source 'my.cnf.erb'
  notifies :restart, 'mysql_service[foo]'
  action :create
end
```

**Comment by micmicsuarez** [comment]
I got the same issue here.

### Cookbook version
8.0.2
### Chef-client version

12.13.37

### Platform Details
CentOS 6.7

### Recipe
I used the sample recipe in `mysql` cookbook documentation.

```ruby
mysql_service 'foo' do
  port '3306'
  version '5.5'
  initial_root_password 'changeme'
  action [:create, :start]
end

mysql_config 'foo' do
  source 'my.cnf.erb'
  notifies :restart, 'mysql_service[foo]'
  action :create
end
```

**Comment by micmicsuarez** [comment]
hi @free0ldman, I made it work by using the old version of mysql. I tested it both `CentOS 6.7` and `CentOS 6.8`.

I added this in `metadata.rb`.

```
depends 'mysql', '~> 6.0'
```

**Comment by shreyasgune** [comment]
This workaround works! I still wonder why the later versions of mysql won't work.
