### ISSUE TITLE
New ubuntu mysql server version for 5.7

### ISSUE THREAD

**Issue by MassiveHiggsField** [chef-cookbooks/mysql#471]
### Cookbook version
latest

### Chef-client version
12.13.37

### Platform Details
Ubuntu 16.04

### Scenario:
Install mysql server 5.7

### Steps to Reproduce:
Install mysql server 5.7 on an ubuntu xenial base system

### Expected Result:
Mysql Server 5.7 gets installed

### Actual Result:
Install fails with: "Version '5.7.13-0ubuntu0.16.04.2' for 'mysql-server-5.7' was not found"

Is there a way to overwrite the default package version? And if there isn't, why not? If PR is welcome i could add an extra prop, maybe "explicit_package_version" or similar.

**Comment by wilb** [comment]
Just hit this myself. Looks like they're hardcoded in libraries/helpers.rb

      # ubuntu
      return '5.5.50-0ubuntu0.12.04.1' if major_version == '5.5' && precise?
      return '5.5.50-0ubuntu0.14.04.1' if major_version == '5.5' && trusty?
      return '5.6.31-0ubuntu0.14.04.2' if major_version == '5.6' && trusty?
      return '5.7.13-0ubuntu0.16.04.2' if major_version == '5.7' && xenial?

...and can be overridden with:

    `property :package_version, [String, nil], default: lazy { default_package_version }, desired_state: false`

Not sure why versions are being hardcoded - isn't it best to let the package manager be responsible for the minor version?

**Comment by wilb** [comment]
`package_version '5.7.15-0ubuntu0.16.04.1'` in your `mysql_service` resource fixes it, theoretically you'll need to do the same for your `mysql_client` too however it seems to be ignoring it in my test recipe and still trying to install `5.7.13-0ubuntu0.16.04.2`

**Comment by MassiveHiggsField** [comment]
letting the package manager decide seems to be the better idea.

**Comment by wilb** [comment]
I'm almost certain that was the default behaviour prior to the refactor to this being a library cookbook; I can understand why there is an option to explicitly define the package version, but the default behaviour shouldn't break when a security fix is published by the distro.

**Comment by wilb** [comment]
This also breaks the mysql2_chef_gem cookbook as it calls the mysql_client resource with the default params.

**Comment by wilb** [comment]
https://github.com/chef-cookbooks/mysql/pull/473

**Comment by flatrocks** [comment]
Now the cookbook expects **5.7.15**-0ubuntu0.16.04.1, but the MySQL version moves on to **5.7.16**-0ubuntu0.16.04.1.

It will be a daily crap-shoot whether or not this cookbook will work, @MassiveHiggsField is right!
