### ISSUE TITLE
Failure on Debian 8.4, mismatched version number

### ISSUE THREAD

**Issue by LiamK** [chef-cookbooks/mysql#479]
### Cookbook version
8.0.3

### Chef-client version
12.13.37

### Platform Details
Debian 8.4 (AWS ami-98e114f8) 

### Scenario:
Trying to install MySQL 5.5

### Steps to Reproduce:
mysql_service db_dbname do
  port '3306'
  version '5.5'
  initial_root_password db_root_password
  action [:create, :start]
end

### Expected Result:
Running MySQL daemon

### Actual Result:
The mysql-server package is not retrieved.   The error log has scrolled out of my life, but the problem was that the wrong minor version is used.
In helpers.rb, line 183, the version is specified as 5.5.49-0.  
That version is not available via the apt package manager. 
I changed the number to 5.5.52-0 and it worked.

Setting the version in the lwrp only works for the major number.  It would have been more convenient to be able to set the minor number there as well.
Maybe a fallback to the default major version number (i.e. 5.5)  in cases where the package is not found?

**Comment by PrimarDarren** [comment]
Should be fixed when pull request #478 is merged.
