### ISSUE TITLE
The version attribute is noot working while installing mysql 

### ISSUE THREAD

**Issue by rsiwal** [chef-cookbooks/mysql#495]
### Cookbook version
8.1.1

### Chef-client version
12.16.42

### Platform Details
  "platform": "centos",
  "platform_version": "7.2.1511",
  "platform_family": "rhel",
      "platform": "x86_64-linux",

### Scenario:
I am not able to install mysql 5.6 . It installs 5.7

### Steps to Reproduce:
Enable yum-mysql-community chef cookbooks and install mysql on the client with the following recipe:
    mysql_service("default") do
      action [:create, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :mysql_service
      cookbook_name "mysql"
      recipe_name "default"
      version "5.6"
      bind_address "0.0.0.0"
      port "3306"
      data_dir "/var/lib/mysql/db"
      initial_root_password "xxxxxx"
      install_method "auto"
      service_manager "auto"
    end
    

### Expected Result:
It should have installed mysql 5.6 community edition

### Actual Result:
It installs mysql 5.7
mysql-community-server-5.7.16-1.el7.x86_64

**Comment by tas50** [comment]
Do you have a repo setup to provide 5.6 on your host?

**Comment by cheeseplus** [comment]
This is almost definitely due to the package manager not being setup correctly prior to the mysql_service call. As it's been several months without response we're closing this one but feel free to open a new issue should the behavior present itself with current versions.
