### ISSUE TITLE
MySQL install hangs on CentOS 7.3

### ISSUE THREAD

**Issue by GreyArea765** [chef-cookbooks/mysql#514]
### Cookbook version
8.2.0

### Chef-client version
12.19.36

### Platform Details
CentOS Linux release 7.3.1611 (Core) 

### Scenario:
Install mysql-server

### Steps to Reproduce:
I have installed the mysql57-community-release.noarch repository and created the following recipe file:

```
# Configure the MySQL client.
mysql_client 'default' do
  version '5.5'
  action :create
end

# Configure the MySQL service
mysql_service 'default' do
  version '5.5'
  initial_root_password node['awesome_customers_centos']['database']['root_password']
  action [:create, :start]
end
```

### Expected Result:
mysql-server to be installed

### Actual Result:
recipe hangs on the following message:
```
       [execute] 2017-02-28 13:49:17 [WARNING] mysql_install_db is deprecated. Please consider switching to mysqld --initialize
                  /tmp/chef-script20170228-2358-wye5f0: line 15: /usr/bin/mysqld_safe: No such file or directory
```

Full chef log here:

[logmysqlfail.txt](https://github.com/chef-cookbooks/mysql/files/806927/logmysqlfail.txt)

**Comment by iennae** [comment]
I tried to replicate your issue and I'm not seeing a problem.
This was the recipe I used:

include_recipe 'yum-mysql-community::mysql55'

# Configure the MySQL client.
mysql_client 'default' do
  version '5.5'
  action :create
end

# Configure the MySQL service
mysql_service 'default' do
  version '5.5'
  initial_root_password node['awesome_customers_centos']['database']['root_password']
  action [:create, :start]
end

       [2017-03-01T06:18:22+00:00] INFO: Chef Run complete in 77.939440369 seconds

       Running handlers:
       [2017-03-01T06:18:22+00:00] INFO: Running report handlers
       Running handlers complete
       [2017-03-01T06:18:22+00:00] INFO: Report handlers complete
       Chef Client finished, 28/40 resources updated in 01 minutes 20 seconds
       Finished converging <default-centos-73> (1m53.80s).

In your attached log it shows that you are installing 5.7

             - install version 5.7.17-1.el7 of package mysql-community-devel
             - install version 5.7.17-1.el7 of package mysql-community-client

Can you take a look at the rest of your recipe and fix how you install the repo?

**Comment by GreyArea765** [comment]
Thank you, I wasn't aware of the yum-community-mysql recipe and was using the one from Oracle which is supposed to include 5.5.

Anyway, I applied your version of the repo recipe and it's all working.

Regards,
Matt

**Comment by iennae** [comment]
Fantastic. Glad that it's working for you!
