### ISSUE TITLE
Could not retrieve mirrorlist https://repo.mysql.com/yum/mysql-5.5-community/el/latest/x86_64/

### ISSUE THREAD

**Issue by stuartweir** [chef-cookbooks/mysql#517]
### Cookbook version
8.2

### Chef-client version
12.5.1

### Platform Details
Amazon Linux on EC2 m3.medium

### Scenario:
Trying to use the mysql cookbook, but the git yum package errors out on me, stating that it cannot retrieve the mirrorlist for the mysql-5.5-community edition

### Expected Result:
I expected that the cookbook would have the right mirrorlist link. If it has changed, this should be updated in the cookbook. Also, it's unclear whether or not I need to use the `yum_mysql_community` cookbook for Amazon EC2 Linux.

### Actual Result:
[* yum_package[git] action install

    ================================================================================
    Error executing action `install` on resource 'yum_package[git]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/python2.7 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
    STDOUT: [option installonlypkgs] kernel kernel-devel kernel-source installonlypkg(kernel) installonlypkg(kernel-module) installonlypkg(vm)
    Could not retrieve mirrorlist https://repo.mysql.com/yum/mysql-5.5-community/el/latest/x86_64/ error was
    14: PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
    STDERR: yum-dump Repository Error: Cannot find a valid baseurl for repo: mysql55-community/latest/x86_64
    ---- End output of /usr/bin/python2.7 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
    Ran /usr/bin/python2.7 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1

    Resource Declaration:
    ---------------------
    # In /home/ec2-user/chef-solo/cookbooks-3/base/recipes/github-deploy.rb

      3: package 'git'
      4:

    Compiled Resource:
    ------------------
    # Declared in /home/ec2-user/chef-solo/cookbooks-3/base/recipes/github-deploy.rb:3:in `from_file'

    yum_package("git") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "git"
      flush_cache {:before=>false, :after=>false}
      declared_type :package
      cookbook_name :base
      recipe_name "github-deploy"
    end]

**Comment by iennae** [comment]
Hi, 

It looks like you are using the yum_mysql_community cookbook and that this is a problem due to using an Amazon 2017 image which will mistakenly use latest rather than "6". The version 2.1.0 of the yum_mysql_community cookbook should resolve your problem. If you are not using that cookbook, then whatever you are doing to set the repo configuration you need to update.
