### ISSUE TITLE
Unable to login as root user for MySQL 5.7 under Ubuntu 16.04, but must use 5.7 because earlier versions not supported.

### ISSUE THREAD

**Issue by awiebe** [chef-cookbooks/mysql#519]
### Cookbook version
8.3

### Chef-client version
Chef Development Kit 1.2.22 chef_solo

### Platform Details
 Ubuntu-16.04 (Xenial) - Vagrant

### Scenario:
Cannot log into mysql server from mysql client.

Ubuntu 16.04 does not have a mysql version 5.5, so 5.7 must be used.  Something is wrong with setting the root password in 5.7.

```
#The string provided on the cookbook did not work used lower requirement
depends 'mysql', '>= 6.1.3' 
mysql_service 'mysql' do
  port '3306'
  version '5.7'
  initial_root_password 'hello'
  action [:create, :start,:restart]
end

```
### Steps to Reproduce:

-Download latest chef cookbook
-Create a vagrant with Ubuntu-16.04
-Set chef recipe parameters as shown above

```
vagrant up --provision
vagrant ssh
mysql -uroot -h127.0..0.1 -phello
```

### Expected Result:
Mysql installed and can log in

### Actual Result:
Mysql is installed but it is impossible to use because the root account is not accessible.

**Comment by iennae** [comment]
Can you provide the error that you are receiving?

**Comment by awiebe** [comment]
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by iennae** [comment]
I've replicated the test using the following recipe:

> apt_update 'update packages'
> 
> mysql_service 'default' do
>   version '5.7'
>   initial_root_password 'potato'
>   action [:create, :start]
> end

It works fine:

> vagrant@default-ubuntu-1604:~$ mysql -u root -h 127.0.0.1 -p
> Enter password:
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Your MySQL connection id is 4
> Server version: 5.7.17-0ubuntu0.16.04.1 (Ubuntu)
> 
> Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> affiliates. Other names may be trademarks of their respective
> owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql>

or password at the command line

> vagrant@default-ubuntu-1604:~$ mysql -u root -h 127.0.0.1 -ppotato
> mysql: [Warning] Using a password on the command line interface can be insecure.
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Your MySQL connection id is 5
> Server version: 5.7.17-0ubuntu0.16.04.1 (Ubuntu)
> 
> Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> affiliates. Other names may be trademarks of their respective
> owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql> quit

When re-examining your message it looks like you have an extra "." in 127.0.0.1. Maybe that is your issue?

**Comment by awiebe** [comment]
No, unfortunately that was a typo.  Since this is an academic project I can provide the precise configuration files.  But being that you seem to have managed to do it without much trouble I'll start by trying a fresh box with nothing but this recipe and see if the problem persists.

**Comment by iennae** [comment]
The rest of my steps are 

chef generate cookbook test-mysql

Make sure that my .kitchen.yml file is platform ubuntu-16.04

My metadata.rb has the following added line:

depends 'mysql'

All I did was kitchen converge ubuntu-16.04, kitchen login, and then ran the mysql -u command as above.

**Comment by awiebe** [comment]
I have painstakingly rebuilt chef box and found it has something to do with use of the mysql cookbook in combination with openssl and/or apache2.  I have yet to isolate the specifics.
