### ISSUE TITLE
centos upgrade

### ISSUE THREAD

**Issue by KGNaidu** [chef-cookbooks/mysql#525]
can't able to upgrade Centos 6.5 to Centos 7 using Redhat-upgrade-tool, any help on this?? 
getting this error:  downloading failed: invalid data in .treeinfo: no option 'upgrade' in section: 'images-x86_64'

**Comment by tas50** [comment]
@KGNaidu I'm not sure how this issue is related to this cookbook. It seems like a Redhat upgrade tool issue that you should take up with Redhat.
