### ISSUE TITLE
Chef never successfully completed!

### ISSUE THREAD

**Issue by conor123** [chef-cookbooks/mysql#534]
### Cookbook version
8.5.1

### Chef-client version
chef-13.5.3-1.el7 

### Platform Details
vagrant bento/centos-7.2
### Scenario:
Install create start 
### Steps to Reproduce:
vagrant provision

### Expected Result:
mysql to install

### Actual Result:
Chef never successfully completed!

==> default:   * mysql_service[default] action create
==> default:     * mysql_server_installation_package[default] action install
==> default: 
==> default:       * yum_package[mysql-community-server] action install
==> default: 
==> default:         * No candidate version available for mysql-community-server
==> default:         ================================================================================
==> default:         Error executing action `install` on resource 'yum_package[mysql-community-server]'
==> default:         ================================================================================
==> default:         
==> default:         Chef::Exceptions::Package
==> default:         -------------------------
==> default:         No candidate version available for mysql-community-server
==> default:         
==> default:         Resource Declaration:
==> default:         ---------------------
==> default:         # In /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb
==> default:         
==> default:          17:       package new_resource.package_name do
==> default:          18:         version new_resource.package_version if new_resource.package_version
==> default:          19:         options new_resource.package_options if new_resource.package_options
==> default:          20:         notifies :install, 'package[perl-Sys-Hostname-Long]', :immediately if platform_family?('suse')
==> default:          21:         notifies :run, 'execute[Initial DB setup script]', :immediately if platform_family?('suse')
==> default:          22:         action :install
==> default:          23:       end
==> default:          24: 
==> default:         
==> default:         Compiled Resource:
==> default:         ------------------
==> default:         # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb:17:in `block in <class:MysqlServerInstallationPackage>'
==> default:         
==> default:         yum_package("mysql-community-server") do
==> default:           package_name "mysql-community-server"
==> default:           action [:install]
==> default:           default_guard_interpreter :default
==> default:           declared_type :package
==> default:           cookbook_name "wordpress"
==> default:         end
==> default:         
==> default:         System Info:
==> default:         ------------
==> default:         chef_version=13.5.3
==> default:         platform=centos
==> default:         platform_version=7.2.1511
==> default:         ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
==> default:         program_name=chef-client worker: ppid=8997;start=19:56:44;
==> default:         executable=/opt/chef/bin/chef-client
==> default:         
==> default: [2017-10-09T19:56:56+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:       
==> default:       ================================================================================
==> default:       Error executing action `install` on resource 'mysql_server_installation_package[default]'
==> default:       ================================================================================
==> default:       
==> default:       Chef::Exceptions::Package
==> default:       -------------------------
==> default:       yum_package[mysql-community-server] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server
==> default:       
==> default:       Resource Declaration:
==> default:       ---------------------
==> default:       # In /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb
==> default:       
==> default:        36:           install = mysql_server_installation(new_resource.name, &block)
==> default:        37:         when 'package'
==> default:       
==> default:       Compiled Resource:
==> default:       ------------------
==> default:       # Declared in /var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb:36:in `installation'
==> default:       
==> default:       mysql_server_installation_package("default") do
==> default:         action [:install]
==> default:         default_guard_interpreter :default
==> default:         declared_type :mysql_server_installation
==> default:         cookbook_name "wordpress"
==> default:         version "5.5"
==> default:         major_version "5.5"
==> default:         package_name "mysql-community-server"
==> default:       end
==> default:       
==> default:       System Info:
==> default:       ------------
==> default:       chef_version=13.5.3
==> default:       platform=centos
==> default:       platform_version=7.2.1511
==> default:       ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
==> default:       program_name=chef-client worker: ppid=8997;start=19:56:44;
==> default:       executable=/opt/chef/bin/chef-client
==> default:       
==> default: [2017-10-09T19:56:56+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'mysql_service[default]'
==> default:     ================================================================================
==> default:     
==> default:     Chef::Exceptions::Package
==> default:     -------------------------
==> default:     mysql_server_installation_package[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Chef::Exceptions::Package: yum_package[mysql-community-server] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/wordpress/recipes/mysql.rb
==> default:     
==> default:       6: mysql_service 'default' do
==> default:       7:   port '3306'
==> default:       8:   version '5.5'
==> default:       9:   initial_root_password 'change me'
==> default:      10:   action [:create, :start]
==> default:      11: end
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/wordpress/recipes/mysql.rb:6:in `from_file'
==> default:     
==> default:     mysql_service("default") do
==> default:       action [:create, :start]
==> default:       default_guard_interpreter :default
==> default:       declared_type :mysql_service
==> default:       cookbook_name "wordpress"
==> default:       recipe_name "mysql"
==> default:       port "3306"
==> default:       version "5.5"
==> default:       initial_root_password "change me"
==> default:     end
==> default:     
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=13.5.3
==> default:     platform=centos
==> default:     platform_version=7.2.1511
==> default:     ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
==> default:     program_name=chef-client worker: ppid=8997;start=19:56:44;
==> default:     executable=/opt/chef/bin/chef-client
==> default:     
==> default: [2017-10-09T19:56:56+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2017-10-09T19:56:56+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-10-09T19:56:56+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 12 seconds
==> default: [2017-10-09T19:56:56+00:00] INFO: Sending resource update report (run-id: d94066a5-fde7-4d3c-9e79-0dc98f04e91e)
==> default: [2017-10-09T19:56:57+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-10-09T19:56:57+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-10-09T19:56:57+00:00] ERROR: mysql_service[default] (wordpress::mysql line 6) had an error: Chef::Exceptions::Package: mysql_server_installation_package[default] (/var/chef/cache/cookbooks/mysql/libraries/mysql_service.rb line 36) had an error: Chef::Exceptions::Package: yum_package[mysql-community-server] (/var/chef/cache/cookbooks/mysql/libraries/mysql_server_installation_package.rb line 17) had an error: Chef::Exceptions::Package: No candidate version available for mysql-community-server
==> default: [2017-10-09T19:56:57+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by iennae** [comment]
Can you provide more information about your configuration here?

Based on the logs here this doesn't seem to be a complete configuration. Checking our test I see that it runs successfully:

>       Thank you for installing Chef!
>        Transferring files to <installation-client-package-55-centos-7>
>        Starting Chef Client, version 13.5.3
>        Creating a new client identity for installation-client-package-55-centos-7 using the validator key.
>        resolving cookbooks for run list: ["selinux::disabled", "mysql_test::yum_repo", "mysql_test::installation_client"]
>        Synchronizing Cookbooks:
>          - mysql_test (0.0.1)
>          - mysql (8.5.1)
>          - yum-mysql-community (2.1.0)
>          - selinux (2.1.0)
>          - compat_resource (12.19.0)
>        Installing Cookbook Gems:
>        Compiling Cookbooks...
>        Converging 5 resources
>        Recipe: selinux::_common
>          * selinux_install[selinux os prep] action install
>            * yum_package[policycoreutils, selinux-policy, selinux-policy-targeted, libselinux-utils, mcstrans] action install
>              - install version 0.3.4-5.el7 of package mcstrans
>            * directory[/etc/selinux] action create (up to date)
> 
>        Recipe: selinux::disabled
>          * selinux_state[SELinux Disabled] action disabled
>            * template[disabled selinux config] action create
>              - update content in file /etc/selinux/config from 80c61e to 8a6a4a
>              --- /etc/selinux/config	2017-08-23 00:12:16.388834000 +0000
>              +++ /etc/selinux/.chef-config20171009-4089-1xdj8ah	2017-10-09 20:32:04.385114737 +0000
>              @@ -1,15 +1,12 @@
>              -
>        # This file controls the state of SELinux on the system.
>        # SELINUX= can take one of these three values:
>              -#     enforcing - SELinux security policy is enforced.
>              -#     permissive - SELinux prints warnings instead of enforcing.
>              -#     disabled - No SELinux policy is loaded.
>              -SELINUX=permissive
>              -# SELINUXTYPE= can take one of three two values:
>              -#     targeted - Targeted processes are protected,
>              -#     minimum - Modification of targeted policy. Only selected processes are protected.
>              -#     mls - Multi Level Security protection.
>              +#       enforcing - SELinux security policy is enforced.
>              +#       permissive - SELinux prints warnings instead of enforcing.
>              +#       disabled - SELinux is fully disabled.
>              +SELINUX=disabled
>              +# SELINUXTYPE= type of policy in use. Possible values are:
>              +#       targeted - Only targeted network daemons are protected.
>              +#       strict - Full SELinux protection.
>        SELINUXTYPE=targeted
>              -
> 
>              - restore selinux security context
> 
>        Recipe: yum-mysql-community::mysql55
>          * yum_repository[mysql55-community] action create
>            * template[/etc/yum.repos.d/mysql55-community.repo] action create
>              - create new file /etc/yum.repos.d/mysql55-community.repo
>              - update content in file /etc/yum.repos.d/mysql55-community.repo from none to 25d437
>              --- /etc/yum.repos.d/mysql55-community.repo	2017-10-09 20:32:04.450144329 +0000
>              +++ /etc/yum.repos.d/.chef-mysql55-community20171009-4089-1ebwy45.repo	2017-10-09 20:32:04.450144329 +0000
>              @@ -1 +1,12 @@
>              +# This file was generated by Chef
>              +# Do NOT modify this file by hand.
>              +
>              +[mysql55-community]
>              +name=MySQL 5.5 Community Server
>              +baseurl=http://repo.mysql.com/yum/mysql-5.5-community/el/$releasever/$basearch/
>              +enabled=1
>              +failovermethod=priority
>              +fastestmirror_enabled=0
>              +gpgcheck=1
>              +gpgkey=https://raw.githubusercontent.com/chef-cookbooks/yum-mysql-community/master/files/default/mysql_pubkey.asc
>              - change mode from '' to '0644'
>              - restore selinux security context
>            * execute[yum clean metadata mysql55-community] action run
>              - execute yum clean metadata --disablerepo=* --enablerepo=mysql55-community
>            * execute[yum-makecache-mysql55-community] action run
>              - execute yum -q -y makecache --disablerepo=* --enablerepo=mysql55-community
>            * ruby_block[yum-cache-reload-mysql55-community] action create
>              - execute the ruby block yum-cache-reload-mysql55-community
>            * execute[yum clean metadata mysql55-community] action nothing (skipped due to action :nothing)
>            * execute[yum-makecache-mysql55-community] action nothing (skipped due to action :nothing)
>            * ruby_block[yum-cache-reload-mysql55-community] action nothing (skipped due to action :nothing)
> 
>        Recipe: mysql_test::installation_client
>          * apt_update[update] action periodic (up to date)
>          * mysql_client_installation_package[default] action create
>            * yum_package[mysql-community-client, mysql-community-devel] action install
>              - install version 5.5.57-2.el7 of package mysql-community-client
>              - install version 5.5.57-2.el7 of package mysql-community-devel
> 
> 
>        Running handlers:
>        Running handlers complete
>        Chef Client finished, 11/16 resources updated in 37 seconds
>        Finished converging <installation-client-package-55-centos-7> (0m54.41s).

Are you including the setup of the mysql repo? i.e.` include_recipe 'yum-mysql-community::mysql55'`

**Comment by conor123** [comment]
@iennae probably not as I'm working off the docs which don't seem to have the right set up. Perhaps you have a better config/setup guide? I have this: https://github.com/chef-cookbooks/mysql/blob/master/README.md No mention of include_recipe 'yum-mysql-community::mysql55' but when i do I get different error: ERROR: could not find recipe default for cookbook yum-mysql-community

**Comment by iennae** [comment]
@conor123 You would need to add a dependency in your cookbook (in the metadata.rb file) to the yum-mysql-community cookbook as done in the test cookbook here:

https://github.com/chef-cookbooks/mysql/blob/master/test/cookbooks/mysql_test/metadata.rb

**Comment by conor123** [comment]
@iennae yep that works, thanks a million. A few people seem to be caught out by that, maybe add it to that readme? Or refer to the test metadata file as above? I am good anyhow, hopefully others will read this and save some time :-)
